name: Roomantics
description: A modern Flutter app for room design and management.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2

  flutter_staggered_animations: ^1.1.0
  flutter_svg: ^2.1.6

  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  provider: ^6.1.1


  # Firebase - Ultra stable versions
  firebase_core: ^4.2.0
  firebase_auth: ^6.0.0
  firebase_storage: ^13.0.0
  cloud_firestore: ^6.0.0
  firebase_app_check: ^0.4.1

  cloudinary: ^1.0.0
  google_sign_in: ^7.2.0
  image_picker: ^1.2.0
  image_picker_android: ^0.8.9+1
  image_picker_platform_interface: ^2.9.3
  model_viewer_plus: ^1.0.0

  camera: ^0.10.5

  path: ^1.8.3
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  ar_flutter_plugin: ^0.7.3

  device_info_plus: ^9.0.0
  package_info_plus: ^4.0.0
  http: ^1.2.0

dependency_overrides:
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "b1b9e8"
  min_sdk_android: 21

flutter_native_splash:
  color: "#b1b9e8"
  image: assets/icon/splash_icon.png
  android: true
  ios: true
  android_12:
    color: "#b1b9e8"
    image: assets/icon/splash_icon.png

flutter:
  uses-material-design: true
  assets:
    - assets/help_data.json
    - assets/icon/