name: Roomantics
description: A modern Flutter app for room design and management.

publish_to: 'none' # This prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_animations: ^1.1.0
  flutter_svg: ^2.1.6

  # Icons and fonts
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0

  # State management
  provider: ^6.0.5

  # Camera functionality
  camera: ^0.11.2

  # Permissions
  permission_handler: ^12.0.1

  # Local storage for saving user theme preference
  shared_preferences: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/help_data.json


