name: roomantics  # Lowercase with underscores
description: A modern Flutter app for room design and management.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  provider: ^6.0.5
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  google_sign_in: ^7.2.0
  camera: ^0.11.2
  path_provider: ^2.1.1
  permission_handler: ^12.0.1
  shared_preferences: ^2.2.2
  flutter_staggered_animations: ^1.1.0
  flutter_svg: ^2.1.6
  image_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  webview_flutter: ^4.4.2


flutter:
  uses-material-design: true
  assets:
    - assets/help_data.json
    - assets/web/
    - assets/web/index.html
    - assets/web/css/style.css
    - assets/web/js/script.js